smoke 1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -376,6 +376,45 @@ jobs:
       - revert-migration:
           workflowId: ${CIRCLE_WORKFLOW_ID:0:7}
 
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+      - image: cimg/base:stable
+    steps:
+      # Checkout code from git
+      - checkout
+      - install_awscli
+      - install_nodejs
+
+      - run:
+          name: Backend smoke test
+          command: |
+            # your code here
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            if curl -s $API_URL/api/status | grep "ok"
+            then 
+              exit 0 
+            else
+              exit 1
+            fi
+
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then 
+              exit 0
+            else
+              exit 1
+            fi
+      - destroy-environment:
+          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}   
+      - revert-migration:
+          workflowId: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Here's where you will add some code to rollback on failure  
 
 
 workflows:
@@ -408,3 +447,7 @@ workflows:
         - deploy-backend:
             requires:
               - run-migration
+        - smoke-test:
+            requires:
+              - deploy-frontend
+              - deploy-backend
